USE [master]
GO
/****** Object:  Database [VtsMSSQLDb]    Script Date: 7/18/2017 2:46:59 PM ******/
CREATE DATABASE [VtsMSSQLDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VtsMSSQLDb', FILENAME = N'/var/opt/mssql/data/VtsMSSQLDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VtsMSSQLDb_log', FILENAME = N'/var/opt/mssql/data/VtsMSSQLDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [VtsMSSQLDb] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VtsMSSQLDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VtsMSSQLDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VtsMSSQLDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [VtsMSSQLDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [VtsMSSQLDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VtsMSSQLDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET RECOVERY FULL 
GO
ALTER DATABASE [VtsMSSQLDb] SET  MULTI_USER 
GO
ALTER DATABASE [VtsMSSQLDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [VtsMSSQLDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [VtsMSSQLDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [VtsMSSQLDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [VtsMSSQLDb] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'VtsMSSQLDb', N'ON'
GO
ALTER DATABASE [VtsMSSQLDb] SET QUERY_STORE = OFF
GO
USE [VtsMSSQLDb]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [VtsMSSQLDb]
GO
/****** Object:  Table [dbo].[Addresses]    Script Date: 7/18/2017 2:46:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Addresses](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[City] [nvarchar](50) NOT NULL,
	[ZipCode] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_Addresses] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Owners]    Script Date: 7/18/2017 2:47:00 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Owners](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[AddressId] [int] NULL,
 CONSTRAINT [PK_Owners] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Products]    Script Date: 7/18/2017 2:47:00 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](500) NULL,
	[Quantity] [int] NOT NULL,
	[OwnerId] [int] NOT NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Owners]  WITH CHECK ADD  CONSTRAINT [FK_Owners_Addresses] FOREIGN KEY([Id])
REFERENCES [dbo].[Addresses] ([Id])
GO
ALTER TABLE [dbo].[Owners] CHECK CONSTRAINT [FK_Owners_Addresses]
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Products_Owners] FOREIGN KEY([Id])
REFERENCES [dbo].[Owners] ([Id])
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_Owners]
GO
USE [master]
GO
ALTER DATABASE [VtsMSSQLDb] SET  READ_WRITE 
GO
